//
module.exports = {
  usuarios: [
    {
      profilePicture:
        "https://pickaface.net/gallery/avatar/urmo12345495bb03d1e37.png",
      name: "Santiago",
      lastName: "Ostrovsky",
      email: "santielgato@gmail.com",
      paiseId: "3de8c1a5-1383-4114-bb6b-93f877473dbd",
      city: "Buenos Aires",
      linkedIn: "",
      gitHub: "",
      webSite: "",
      yearsOfExperience: 1,
      dailyBudget: 20,
      englishLevel: "Intermedio",
      bio: "",
      servicios: ["14d10f6a-2965-4d8b-ac25-106dbd3096d4"],
      lenguajes: ["fd25c40a-b07d-4664-bbae-7c74a3e37d39"],
      tecnologias: ["c09c0e66-2816-4f06-a9ca-462cccf636f6"],
    },
    {
      profilePicture:
        "https://pickaface.net/gallery/avatar/urmo12345495bb03d1e37.png",
      name: "Francisco",
      lastName: "Navarro",
      email: "fran271214201211@gmail.com",
      paiseId: "3de8c1a5-1383-4114-bb6b-93f877473dbd",
      city: "Mar del Plata",
      linkedIn: "",
      gitHub: "",
      webSite: "",
      yearsOfExperience: 2,
      dailyBudget: 30,
      englishLevel: "Intermedio",
      bio: "",
      servicios: ["0d9935f5-5735-4480-ab89-ea1fc22aa13"],
      lenguajes: ["4e426313-a49b-44b6-a692-b8ef23e98fd6"],
      tecnologias: ["8ae0dac6-5267-49fc-94d3-1a32723ca83e"],
    },
    {
      profilePicture:
        "https://pickaface.net/gallery/avatar/urmo12345495bb03d1e37.png",
      name: "Ramiro",
      lastName: "Ferradas",
      email: "ramielgato@gmail.com",
      paiseId: "3de8c1a5-1383-4114-bb6b-93f877473dbd",
      city: "Rafaela",
      linkedIn: "",
      gitHub: "",
      webSite: "",
      yearsOfExperience: 3,
      dailyBudget: 40,
      englishLevel: "Profesional",
      bio: "",
      servicios: ["95d4eafe-c6bc-4292-a06f-c26f103d1436"],
      lenguajes: ["09be53ce-5d6a-4d2f-bb1b-c270cdcda95c"],
      tecnologias: ["e99fb4df-d6a7-4ebc-b029-472581981820"],
    },
  ],
  paises: [
    "Argentina",
    "Bolivia",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Ecuador",
    "El Salvador",
    "Guatemala",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Puerto Rico",
    "Republica Dominicana",
    "Uruguay",
    "Venezuela",
  ],
  servicios: [
    "AR / VR",
    "Artificial Intelligence",
    "Blockchain",
    "System Management & Logistics",
    "Data Engineer",
    "Data Science",
    "Databases",
    "Desktop Apps (IOS)",
    "Desktop Apps (Linux)",
    "Desktop Apps (Windows)",
    "Desktop Apps (Other)",
    "DevOps",
    "Games",
    "IT Security",
    "Machine Learning",
    "Mobile Apps (Android)",
    "Mobile Apps (IOS)",
    "Mobile Apps (Other)",
    "Product Design",
    "Quality Assurance (Manual)",
    "Quality Assurance (Full Stack)",
    "Responsive Design",
    "RPA",
    "Salesforce",
    "UI / UX",
    "Web (Back-end)",
    "Web (Front-end)",
    "Web (Full Stack)",
  ],
  lenguajes: [
    "ABAP",
    "Ada",
    "Apex",
    "Assembly Language",
    "Bash",
    "C#",
    "C++",
    "C",
    "Clojure",
    "Cobol",
    "D",
    "Dart",
    "Delphi",
    "F#",
    "Fortran",
    "FoxPro",
    "G/LabVIEW",
    "Go",
    "Groovy",
    "Haskell",
    "Java",
    "JavaScript",
    "Julia",
    "Kotlin",
    "Ladder Logic",
    "Lisp",
    "Logo",
    "Lua",
    "Matlab",
    "Nim",
    "Objective-C",
    "Pascal",
    "Perl",
    "PHP",
    "PL/SQL",
    "Prolog",
    "Python",
    "R",
    "Ruby",
    "Rust",
    "SAS",
    "Scala",
    "Scheme",
    "Scratch",
    "SQL",
    "Swift",
    "Transact-SQL",
    "TypeScript",
    "VBA",
    "VBScript",
    "VHDL",
    "Visual Basic",
  ],
  tecnologias: [
    "8th Dev",
    "A-Frame",
    "Accelo",
    "Accord.Net",
    "Active Collab",
    "ADABAS",
    "Advent",
    "Adventure Games Studio",
    "Airflow",
    "Airtest",
    "Altibase",
    "Amazon Machine Learning",
    "Anaconda",
    "Angular",
    "Ansible",
    "Apache Airflow",
    "Apache Cordova",
    "Apache Hadoop",
    "Apache Hive",
    "Apache Kafka",
    "Apache Mahout",
    "Apache Maven",
    "Apache MXNet",
    "Apache Spark",
    "Appcelerator",
    "Apptivo",
    "ARcore",
    "Argon",
    "Artifactory",
    "ASP.NET",
    "ASP.NET core",
    "Atlassian JIRA",
    "Autodesk StingRay",
    "Automation Anywhere",
    "AWS Athena",
    "AWS Deep Learning AMI",
    "AWS EMR",
    "AWS Glue",
    "Backbone",
    "Bamboo",
    "Basecamp",
    "Basic4Android",
    "Basis Technologies",
    "Beego",
    "BI",
    "Bit.ai",
    "Bitcoin",
    "Bitrix24",
    "Blender",
    "Blue Prism",
    "BlueCamroo",
    "Bokeh",
    "Bootstrap",
    "Buddy",
    "Caffe / Caffe 2",
    "CakePHP",
    "Capistrano",
    "Carbon",
    "Cassandra",
    "CeltX",
    "CFEngine",
    "Chainer",
    "Character Creator Pipeline",
    "Chef",
    "CircleCI",
    "Clarizen",
    "ClickUp",
    "Cloudera",
    "CMMC",
    "COBIT",
    "Code Climate",
    "CodeIgniter",
    "Codeigniter",
    "Connecteam",
    "Construct 2",
    "Consul",
    "Corda",
    "Corona SDK",
    "Corona SDK / Solar 2D",
    "CounchDB",
    "CryENGINE",
    "Daba Build Tool",
    "Datadog",
    "Daz3D",
    "DeepLearning4j",
    "Defold Engine",
    "Deltek",
    "Deno",
    "Django",
    "Docker",
    "Dojo Mobile",
    "ElasticSearch",
    "Electron",
    "ELK Stack",
    "Ember",
    "Enact",
    "EOS",
    "Ethereum",
    "Exonum",
    "Express",
    "Famo.us",
    "Fast.ai",
    "Favro",
    "FFIEC CAT",
    "Fiber",
    "Firebase",
    "FISMA",
    "Fivetran",
    "Flame",
    "Flask",
    "Flink",
    "Flodesk",
    "FlowLab",
    "Flutter",
    "Flutter on Desktop",
    "Foundation",
    "Frank",
    "GameBench",
    "GameFroot",
    "GameMaker",
    "GameSalad",
    "Ganglia",
    "GDevelop",
    "GDPR",
    "Gin Gonic",
    "Git",
    "GitBash",
    "GitKraken",
    "GitUI",
    "Gluon",
    "Godot Engine",
    "Google Cloud BigQuery",
    "Gradle",
    "Graylog",
    "H2O",
    "Hadoop HDFS",
    "Haxe",
    "HelixCore",
    "Heroku",
    "HITRUST CSF",
    "HoneyBook",
    "Horovod",
    "Houdini FX",
    "HubSpot CRM",
    "Huggingface",
    "Hyperledger Burrow",
    "Hyperledger Fabric",
    "Hyperledger Indy",
    "Hyperledger Iroha",
    "Hyperledger Sawtooth",
    "IASME Governance",
    "iBE.net",
    "IBM Db2",
    "IBM Rational Functional Tester",
    "IBM RPA",
    "Icinga",
    "Incredibuild",
    "Insightly",
    "Ionic",
    "iOS Arkit",
    "IOTA",
    "IPython Notebook",
    "Iris",
    "JavaFX",
    "Jenkins",
    "Jest",
    "JQuery",
    "JQuery Mobile",
    "Juju",
    "Jupyter Notebook",
    "Kafka",
    "Kendo UI",
    "Keras",
    "Keyshot",
    "Kibana",
    "Koa",
    "Krita",
    "Kubernetes",
    "Kudan",
    "Laravel",
    "Leadwerks",
    "LibGDX",
    "Light GBM",
    "Logstash",
    "Looker",
    "Lumberyard",
    "Lumen",
    "MariaDB",
    "Materialize",
    "Matplotlib",
    "MERN",
    "Meteor",
    "Microsoft Cognitive Toolkit",
    "Microsoft SQLServer",
    "Milligram",
    "Mixamo",
    "Mobile Angular UI",
    "MongoDB",
    "Monit",
    "MXNET",
    "MySQL",
    "Nagios",
    "Native Scripts",
    "Natural Language Toolkit",
    "NEM",
    "Neo4j",
    "NestJs",
    "Netsuite",
    "Neutralinojs",
    "New Relic APM",
    "Next",
    "NIST CSF",
    "NIST RMF",
    "Node",
    "Novashell",
    "nTask",
    "NumPy",
    "Odoo",
    "OneSoft Connect",
    "ONNX",
    "Onsen UI",
    "Open RPA",
    "OpenRA",
    "Oracle",
    "OrientDB",
    "Orx",
    "OS.js",
    "OverOps",
    "PagerDuty",
    "Pandas",
    "Paymo",
    "PCI DSS",
    "Pega",
    "Periscope",
    "Phoenix",
    "Phonegap",
    "phpMyAdmin",
    "Pixel Game Maker MV",
    "Pixi.js",
    "Play",
    "Plotly",
    "Podio",
    "PostgreSQL",
    "Power BI",
    "Preact",
    "Presto",
    "Primrose",
    "ProductionMap",
    "Prometheus",
    "ProofHub",
    "ProWorkflow",
    "Puppet",
    "Puppet Enterprise",
    "Pydot",
    "PyTorch",
    "Qlik Sense",
    "QuerySurge",
    "Quixel Bridge",
    "Quorum",
    "Rails",
    "React",
    "React Native",
    "React VR",
    "Redis",
    "RedShift",
    "Redux",
    "RedWood Software",
    "REN'PY",
    "Render",
    "Ripple",
    "RNN",
    "Robomongo",
    "Robot Framework",
    "RPGMaker",
    "Rudder",
    "SAMA Cybersecurity",
    "SAP",
    "SAP Sybase ASE",
    "Scalyr",
    "Scikit Learn",
    "SciPy",
    "Scoro",
    "Seaborn",
    "Segment",
    "Selenium",
    "Semantic UI",
    "Sencha Ext JS",
    "Sencha Touch",
    "Sencha Touch 2",
    "Sensu",
    "Sequel PRO",
    "Sequelize",
    "Shogun",
    "Simple CV",
    "Slim",
    "SmartSheet",
    "Snort",
    "Snowflake",
    "SoapUI",
    "Solarwinds DevOps",
    "SpaCy",
    "Spark",
    "Spark MLib",
    "SpatialOS",
    "SpeedTree",
    "Splunk",
    "Spring",
    "Spring Boot",
    "Sproutcore MVC",
    "SQLite",
    "Stackify Retrace",
    "Stencyl",
    "Stitch",
    "Strapi",
    "Strata Sculpt 3D",
    "StudioCloud",
    "Sumo Logic",
    "Supervisor",
    "Svelte",
    "Swiftic",
    "Swing",
    "Symphony",
    "Tableau",
    "TagUI",
    "Taskt",
    "Tauri",
    "TeamCity",
    "Teamleader",
    "Tensor Flow",
    "Teradata",
    "Terraform",
    "TestSigma",
    "Theano",
    "Theappbuilder",
    "Thryv",
    "Timecamp",
    "Timely",
    "Toad",
    "Todo.vu",
    "Torch",
    "Torque 3D",
    "Travis CI",
    "Trello",
    "Tricentis Tosca",
    "Twine",
    "UI.Vision",
    "UIKit",
    "UiPath",
    "Unity",
    "Unreal Engine",
    "UpGuard",
    "Urho 3D",
    "UWP",
    "Vagrant",
    "ValveSoftware",
    "Veles",
    "Vercel",
    "Verint RPA",
    "Vue",
    "Vuforia",
    "Waves",
    "Webpack",
    "WebVR",
    "Wick Editor",
    "Wikitude SDK",
    "WORKetc",
    "WorkFusion",
    "WPF Toolkit",
    "Xamarin",
    "Xamarin.Forms",
    "Xgboost",
    "Xojo",
    "Zoho One",
  ],
};

// update
